@hostname = localhost
@port = 3000
@host = http://{{hostname}}:{{port}}

### Register a new user
POST http://localhost:3000/rekisteroi
Content-Type: application/x-www-form-urlencoded

username=testi&password=salasana

### Get users
GET http://localhost:3000/users
Content-Type: application/json

### Login with the user
POST http://localhost:3000/kirjaudu
Content-Type: application/x-www-form-urlencoded

username=testi&password=salasana

### Logout
POST http://localhost:3000/kirjUlos
Content-Type: application/x-www-form-urlencoded

### Delete user
DELETE http://localhost:3000/api/delete-user

### Create post (Vaatii kirjautumise ensin)
POST http://localhost:3000/api/create-post
Content-Type: application/json

{
    "title": "Kala",
    "content": "Löyty kala järvestä :D"
}

### Like post (päätyyn postin id)
POST http://localhost:3000/api/like-post/1

### Delete post (päätyyn postin id)
DELETE http://localhost:3000/api/delete-post/10

### Get posts
GET http://localhost:3000/api/load-posts?page=1

### Get replies
GET http://localhost:3000/api/load-replies/1

### Post reply
POST http://localhost:3000/api/post-reply/1
Content-Type: application/json

{
    "content": "Hienoa!"
}